### ISSUE TITLE
Missile Doors Don't Close After Launch

### ISSUE THREAD

**Issue by unstoppable777** [Solmex72/NavyCraft-Reloaded#36]
Just a quick thing I noticed while testing my VLS system. After firing the VLS door does not automatically close as they do on torpedoes. This could spell disaster for submarines launching from underwater. I've only tested VLS and not HLS, not sure if HLS has the same problem.

**Comment by ROKA611** [comment]
Due to horizontal missiles blow up upon contact with water. Horizontal missiles are supposed to be used on aircrafts.
