### ISSUE TITLE
Range Bug

### ISSUE THREAD

**Issue by unstoppable777** [Solmex72/NavyCraft-Reloaded#37]
Was testing out a slightly modified launcher design (has nothing to do with the bug), and whilst messing around with the flight range the missile started completely ignoring its setting and always went to 250m no matter its setting. After further testing it seemed this happened after firing on a 0m range setting. 

I took the ship out again and set on 0m it worked fine, so it might be a freak thing that occurred. Maybe worth taking a look at anyway.

**Comment by Solmex72** [comment]
well I'm pretty sure I know why missiles sometimes do that and its because of the way I defined variables that they use to travel. I'll probably adjust this tomorrow and they'll be fine.
