### ISSUE TITLE
Sponge port?

### ISSUE THREAD

**Issue by Terra1** [Solmex72/NavyCraft-Reloaded#39]
It'd be nice to have a sponge port, since Spigot will probably cease development sooner or later, and mods would remove a patently absurd amount of future work (IC2 or Mekanism would make survival shipbuilding significantly easier, ComputerCraft would just be cool, Project Red would make redstone stuff easier, etc)
This would take an absolutely absurd amount of work right now to do, but less than implementing all the stuff made available by mods. Plus, we could rely less on signs since we would have an unlimited amount of blocks to use, and we could make ships more realistic by having multiblock engines instead of engine signs, and we could have working fully-enclosed single and double barrel turrets.

**Comment by Solmex72** [comment]
I mean I can do it, but it's definitely not a priority right now

**Comment by Terra1** [comment]
Not asking you to do it now, just asking you to do it once all the major (and minor) things are done
