### ISSUE TITLE
Vertical Missile Launcher sinking ships only credits the gunner, not entire crew

### ISSUE THREAD

**Issue by Wrangler9033** [Solmex72/NavyCraft-Reloaded#44]
If the vertical missile launcher does the killing blow on a targeted vehicle, the server will ONLY give rp to the person who fired it vs giving it to entire crew of the vehicle on.

**Comment by Solmex72** [comment]
![proof](https://i.gyazo.com/d8d4e3aaac49fb63d7906a63ea82bfe7.png)
