### ISSUE TITLE
Horizontal Missile Launchers - Unable to Reload 

### ISSUE THREAD

**Issue by Wrangler9033** [Solmex72/NavyCraft-Reloaded#45]
The Horizontal Missile Launcher is setup exact same as the Torpedoes. The ring reloader used with the launcher SHOULD work same way, but when you go to use it.  The missile door will lower to allow reloading, but the 2nd lever gives error that the launcher is already Loaded.

**Comment by Solmex72** [comment]
what?

**Comment by Solmex72** [comment]
Missiles don't have a reloading system, the only way to reload them is by hand, and it will probably stay that way.
