### ISSUE TITLE
Torpedo Turning Mechanism

### ISSUE THREAD

**Issue by Wrangler9033** [Solmex72/NavyCraft-Reloaded#47]
When you attach a Torpedo launcher with a Lever, navycraft usually allows the weapon turn, like on a turret.
However, the Horizontal missile launcher does not turn full length of the weapon, cutting off 3 blocks on end and not of the blocks above move with new positioning of the weapon.

**Comment by Terra1** [comment]
That's normal. Torpedoes do that too.
