### ISSUE TITLE
Easy-updating program

### ISSUE THREAD

**Issue by Terra1** [Solmex72/NavyCraft-Reloaded#54]
Basically just a program that, when run, while download the latest "stable" release of NavyCraft Reloaded and replace your current install with it. It would be **very** nice to have, especially for people running small, low budget servers.

**Comment by Solmex72** [comment]
If you want the latest update, you can look at the releases tab and see downloadable jars. If you want to compile it in its heavy developmental stages then you can using eclipse. There's going to be a new release soon so you can download the jar from that.
